### ISSUE TITLE
ae-address style

### ISSUE THREAD

**Issue by emilsomm** [aeternity/aepp-components#243]
When using the `ae-address` component for the redesign of the Blockchain Explorer I have met some problems using this component.

__Expected Behavior:__

what i need is this 

<img width="346" alt="screenshot 2019-01-09 13 14 02" src="https://user-images.githubusercontent.com/20213342/50898811-8d0d4480-1410-11e9-9a27-5c67b7ca282a.png">

__Current Behavior:__

but what im getting is 
<img width="494" alt="screenshot 2019-01-09 13 29 27" src="https://user-images.githubusercontent.com/20213342/50899521-a0211400-1412-11e9-8568-118c2d50ba79.png">

__Possible Solution:__

If we add an option for `style` with `values` such as `flex, grid, flat` and set the width property according to the value of `style` we could achieve the desired look. I also think that `flat` has more to do with `style` than `length` as is currently the case. 

```` css
.ae-address {
    position: relative;
    display: flex;
    align-items: flex-start;
    flex-wrap: wrap;
    font-weight: 500;
    width: 100%;
    height: 100%;
    padding: 0;
    margin: 0;
    /*
    * also would be great to have more control over the font-size as an option, 
    * so the components would inherit from parent component set locally
    * ex:
    * font-size: 1em;
    * or
    * font-size: inherit;
    */
}

.ae-address > li {
    width: 3em;
}
````
<img width="471" alt="screenshot 2019-01-09 13 15 28" src="https://user-images.githubusercontent.com/20213342/50898879-be861000-1410-11e9-87f9-1ac2633b4337.png">
